### ISSUE TITLE
ID not incremented on MySQL and Postgres

### ISSUE THREAD

**Issue by tristancaron** [prisma/prisma2#135]
When you design a new Prisma model for MySQL. The first insert works, the second fail.
```
 UnhandledPromiseRejectionWarning: Error: Error in Photon: 
ConnectorError(UniqueConstraintViolation { field_name: "User.id" })
```

**Comment by pantharshit00** [comment]
I can confirm this. Only happens with integer IDs so you can use UUID or CUID as a workaround

Datamodel for reproduction. Just try creating `User` twice.

```groovy
datasource db {
  provider = "mysql"
  url      = "mysql://root@<redacted>@localhost:3306/issue_120"
}

generator photon {
  provider = "photonjs"
}

type ID = String @id @default(uuid())

model User {
  id         ID
  name       String
  resetToken String
}
```

```js
const Photon = require('@generated/photon')
const crypto = require('crypto')

const photon = new Photon.default()

async function main() {
  const user = await photon.users.create({
    data: {
      name: 'harshit pant',
      resetToken: crypto.randomBytes(10).toString('hex'),
    },
  })
}

main()
```

**Comment by debianmaster** [comment]
same issue with postgreql.   cannot use autoincrement feature of postgres when defining model

**Comment by mabuonomo** [comment]
same issue, there are some fix?

**Comment by jmadson** [comment]
We're also experiencing the same issue w/ auto-increment not working against Postgres. We have an `id` column on every model with the `@id` directive.

Does it make sense to add the auto-increment functionality to the `@id` directive, or should it be something we can pass into `@default` (such as `@id @default(autoIncrement())`)? Just food for thought :)

**Comment by mavilein** [comment]
I looked into this yesterday. We cannot easily fix this as of now. We will have to wait until our internal introspection rewrite has been finished. Then this will be easy to fix. So we will postpone this for a bit.

**Comment by divyenduz** [comment]
Workaround for now: Manually edit the MySQL column to add auto increment property. Example

`ALTER TABLE <table-name> MODIFY COLUMN <column-name> INT auto_increment`
`ALTER TABLE document MODIFY COLUMN document_id INT auto_increment`

**Comment by mavilein** [comment]
This is fixed now. Should be available on `alpha` soon.

**Comment by pantharshit00** [comment]
I can confirm that this has been fixed 🎉

**Comment by tristancaron** [comment]
This still happening for me. 

```
model User {
    id       String @id @default(cuid())
    email String @unique
}
```

Then the first object inserted in the database is passing
```
photon.users.createOne({
    data: {
        email: "joyjoy@site.com",
    },
})
```

But not the second
```
photon.users.createOne({
    data: {
        email: "sadsad@site.com",
    },
})
```

**Comment by pantharshit00** [comment]
@tristancaron 

You might need to reset the database in order to create the index.

**Comment by tristancaron** [comment]
It's happening with a fresh database and SQLite

**Comment by pantharshit00** [comment]
Can you please paste a screenshot of the error.

> photon.users.createOne({
Also, there is no `createOne` method. The method name is `create`. Please make sure that you are on the latest version.

**Comment by tristancaron** [comment]
Tests were passing before update.

All our tests are made with fresh start at the moment.

Here you can see the value for `email` that I'm passing. There is only one entry in the database with a different email value. And I am using the latest version of Prisma.

<img width="713" alt="image" src="https://user-images.githubusercontent.com/9624669/64126464-d6cde500-cd7b-11e9-82ba-8ffa1b3ef543.png">
<img width="786" alt="image" src="https://user-images.githubusercontent.com/9624669/64126506-00870c00-cd7c-11e9-8abc-a2dd89553979.png">

**Comment by pantharshit00** [comment]
The error suggests that a unique constraint is violated on the `s_email` field that means there is a duplicate row with the same email in the database. 

This is certainly not related to this issue.

**Comment by tristancaron** [comment]
But there is nothing in the database... Like I shown you in the previous screenshots. The table has only one row with a different email. And nothing else in the database as a field email.

**Comment by tristancaron** [comment]
<img width="713" alt="64126464-d6cde500-cd7b-11e9-82ba-8ffa1b3ef543" src="https://user-images.githubusercontent.com/9624669/64130545-063b1c80-cd91-11e9-996c-f9a25f405dae.png">

**Comment by pantharshit00** [comment]
Interesting. Can you please share your schema?

**Comment by tristancaron** [comment]
Yes, sure maybe I am doing something wrong, it's starting to be messy ^^'

```
datasource db {
    provider = "sqlite"
    url      = "file:./dev.db"
}

generator photon {
    provider = "photonjs"
}

model Company {
    id             String   @id @map("s_id") @default(cuid())
    createdAt      DateTime @map("dtu_creation") @default(now())
    updatedAt      DateTime @map("dtu_last_update") @updatedAt
    active         Boolean  @map("b_active") @default(true)
    address        String?  @map("s_address")
    country        String?  @map("s_country")
    externalId     String?  @map("s_external_id")
    externalUserId String?  @map("s_external_user_id")
    name           String   @map("s_name")
    pictureUrl     String?  @map("s_picture_url")

    managers  User[]    @relation(name: "tbl_user_manager_to_company")
    followers User[]    @relation(name: "tbl_user_follower_to_company")
    users     User[]
    // many to one
    offers    Offer[]
    // many to one
    ruleSets  RuleSet[] @relation(name: "tbl_rule_set_to_company")
    tags      Tag[]     @relation(name: "tbl_tag_to_company")

    @@map("tbl_companies")
}

model Rule {
    id         String   @id @map("s_id") @default(cuid())
    allowed    Boolean  @map("b_allowed")
    createdAt  DateTime @map("dtu_creation") @default(now())
    type       RuleType @map("e_type")
    resourceId String?  @map("s_resource_id")
    field      String?  @map("s_field")
    collection String   @map("s_table")
    values     String   @map("j_values") @default("[]")

    ruleSets RuleSet[] @relation(name: "tbl_rule_to_rule_set")
    users    User[]    @relation(name: "tbl_rule_to_user")

    @@map("tbl_rules")
}

model RuleSet {
    id          String   @id @map("s_id") @default(cuid())
    hidden      Boolean  @map("b_hidden")
    createdAt   DateTime @map("dtu_creation") @default(now())
    updatedAt   DateTime @map("dtu_last_update") @updatedAt
    description String   @map("s_description")
    name        String   @map("s_name")

    category  Category   @map("s_category_id")
    templates Template[] @relation(name: "tbl_rule_set_to_template")
    users     User[]     @relation(name: "tbl_rule_set_to_user")
    companies Company[]  @relation(name: "tbl_rule_set_to_company")

    rules Rule[] @relation(name: "tbl_rule_to_rule_set")

    @@map("tbl_rule_sets")
}

model Category {
    id          String   @id @map("s_id") @default(cuid())
    createdAt   DateTime @map("dtu_creation") @default(now())
    updatedAt   DateTime @map("dtu_last_update") @updatedAt
    description String   @map("s_description")
    name        String   @map("s_name")

    ruleSets      RuleSet[]
    // many to one
    notifications Notification[]

    @@map("tbl_categories")
}

model Template {
    id          String   @id @map("s_id") @default(cuid())
    createdAt   DateTime @map("dtu_creation") @default(now())
    updatedAt   DateTime @map("dtu_last_update") @updatedAt
    description String   @map("s_description")
    name        String   @map("s_name")

    ruleSets RuleSet[] @relation(name: "tbl_rule_set_to_template")

    @@map("tbl_templates")
}

model User {
    id                String   @id @map("s_id") @default(cuid())
    externalId        String   @map("s_external_id") @default("")
    createdAt         DateTime @map("dtu_creation") @default(now())
    updatedAt         DateTime @map("dtu_last_update") @updatedAt
    role              UserRole @map("e_role") @default(External)
    email             String   @map("s_email") @unique
    name              String   @map("s_name")
    password          String   @map("s_password")
    pictureUrl        String   @map("s_picture_url") @default("")
    title             String   @map("s_title") @default("")
    isProfileComplete Boolean  @map("b_is_profile_complete") @default(false)

    ruleSets               RuleSet[]       @relation(name: "tbl_rule_set_to_user")
    rules                  Rule[]          @relation(name: "tbl_rule_to_user")
    managedCompanies       Company[]       @relation(name: "tbl_user_manager_to_company")
    followedCompanies      Company[]       @relation(name: "tbl_user_follower_to_company")
    managedOffers          Offer[]         @relation(name: "tbl_offer_to_user_manager")
    followedOffers         Offer[]         @relation(name: "tbl_offer_to_user_follower")
    assignedCreativeGroups CreativeGroup[] @relation(name: "tbl_creative_groups_to_assignee")
    approvedCreativeGroups CreativeGroup[] @relation(name: "tbl_creative_groups_to_approver")

    notificationSettings NotificationSetting[]

    company Company? @map("s_company_id")

    @@map("tbl_users")
}

model Event {
    id        String    @id @map("s_id") @default(cuid())
    parentId  String    @map("s_parent_id")
    type      EventType @map("s_type")
    createdAt DateTime  @map("dtu_creation") @default(now())

    info String @map("s_info")

    createdBy User? @map("s_created_by_user_id")

    @@map("tbl_events")
}

model Offer {
    id                   String        @id @map("s_id") @default(cuid())
    name                 String        @map("s_name")
    externalId           String?       @map("s_external_id")
    externalAppId        String        @map("s_external_app_id") @default("")
    externalAppSecret    String        @map("s_external_app_secret") @default("")
    externalAdAccountIds String        @map("a_external_ad_account_ids") @default("[]")
    code                 String        @map("s_code")
    pictureUrl           String        @map("s_picture_url") @default("")
    storeUrl             String        @map("s_store_url")
    description          String        @map("s_description") @default("")
    version              String        @map("s_version") @default("")
    minOSVersion         String        @map("s_min_os_version") @default("")
    notes                String        @map("s_notes") @default("")
    videoRecordingUrls   String        @map("a_video_recording_urls") @default("[]")
    engine               OfferEngine   @map("e_engine")
    priority             OfferPriority @map("e_priority")
    status               OfferStatus   @map("e_status") @default(PendingApproval)
    archived             Boolean       @map("b_archived") @default(false)
    rejectionReason      String        @map("s_rejection_reason") @default("")
    signingReason        String        @map("s_signing_reason") @default("")
    createdAt            DateTime      @map("dtu_creation") @default(now())
    updatedAt            DateTime      @map("dtu_last_update") @updatedAt

    company        Company         @map("s_company_id")
    followers      User[]          @relation(name: "tbl_offer_to_user_follower")
    managers       User[]          @relation(name: "tbl_offer_to_user_manager")
    createdBy      User            @map("i_created_by_user")
    campaigns      Campaign[]
    creativeGroups CreativeGroup[]
    comments       Comment[]
    networks       Network[]


    tags Tag[] @relation(name: "tbl_tag_to_offer")

    @@map("tbl_offers")
}

model File {
    id          String   @id @map("s_id") @default(cuid())
    type        FileType @map("e_file_type")
    name        String   @map("s_name")
    description String   @map("s_description")
    mimeType    String   @map("s_mime_type")
    url         String   @map("s_url")
    createdAt   DateTime @map("dtu_creation") @default(now())
    updatedAt   DateTime @map("dtu_last_update") @updatedAt

    parentId String @map("s_parent_id")

    createdBy User @map("i_created_by_user")

    tags Tag[] @relation(name: "tbl_tag_to_file")

    @@map("tbl_files")
}

model Tag {
    id    String @id @map("s_id") @default(cuid())
    name  String @map("s_name")
    color String @map("s_color")

    offers    Offer[]   @relation(name: "tbl_tag_to_offer")
    files     File[]    @relation(name: "tbl_tag_to_file")
    companies Company[] @relation(name: "tbl_tag_to_company")

    @@map("tbl_tags")
}

model Campaign {
    id          String         @id @map("s_id") @default(cuid())
    status      CampaignStatus @map("e_campaign_status") @default(Waiting)
    externalId  String         @map("s_external_id")
    oses        String         @map("a_device_oses") @default("[]")
    countries   String         @map("a_country_codes") @default("[]")
    description String         @map("s_description") @default("")
    startedAt   DateTime?      @map("dtu_started_at")
    finishedAt  DateTime?      @map("dtu_finished_at")
    createdAt   DateTime       @map("dtu_creation") @default(now())
    updatedAt   DateTime       @map("dtu_last_update") @updatedAt

    createdBy     User            @map("s_created_by_user_id")
    creativeGroup CreativeGroup   @map("s_creative_group_id")
    network       Network         @map("s_network_id")
    result        CampaignResult? @map("s_campaign_result_id")
    offer         Offer?          @map("s_offer_id")

    @@map("tbl_campaigns")
}

model Network {
    id                  String           @id @map("s_id") @default(cuid())
    isChecked           Boolean          @map("b_is_checked")
    isOsStoreLive       Boolean          @map("b_is_os_store_live")
    hasSDK              Boolean          @map("b_has_sdk")
    hasAdAccess         Boolean          @map("b_has_ad_access")
    hasAnalyticsAccess  Boolean          @map("b_has_analytics_access")
    adAccountStatus     AdAccountsStatus @map("e_ad_account_status")
    isLive              Boolean          @map("b_is_live")
    hasPrivacyPolicyUrl Boolean          @map("b_has_privacy_policy_url")
    hasContactEmail     Boolean          @map("b_has_contact_email")
    hasIconUrl          Boolean          @map("b_has_icon_url")
    hasIosBundleId      Boolean          @map("b_has_ios_bundle_id")
    type                NetworkType      @map("e_network_type")

    offer    Offer      @map("s_offer_id")
    campaign Campaign[]

    @@map("tbl_networks")
}

model CreativeGroup {
    id        String               @id @map("s_id") @default(cuid())
    status    CreativeGroupStatus? @map("e_status") @default(New)
    createdAt DateTime             @map("dtu_creation") @default(now())
    updatedAt DateTime             @map("dtu_last_update") @updatedAt

    offer      Offer? @map("s_offer_id")
    assignedTo User?  @relation(name: "tbl_creative_groups_to_assignee") @map("i_assigned_to")
    approvedBy User?  @relation(name: "tbl_creative_groups_to_approver") @map("i_approved_by")

    creatives Creative[]
    campaign  Campaign[]
    comments  Comment[]

    @@map("tbl_creative_groups")
}

model CampaignResult {
    id          String   @id @map("s_id") @default(cuid())
    conversions Int      @map("i_conversions")
    eCPI        Float    @map("f_eCPI")
    eCTR        Float    @map("f_eCTR")
    spend       Float    @map("f_spend")
    createdAt   DateTime @map("dtu_creation") @default(now())
    updatedAt   DateTime @map("dtu_last_update") @updatedAt

    campaign  Campaign? @map("s_campaign_id")
    createdBy User      @map("s_created_by_user_id")

    comments Comment[]

    @@map("tbl_campaign_results")
}

model Creative {
    id       String       @id @map("s_id") @default(cuid())
    name     String       @map("s_name")
    language String       @map("s_language") @default("")
    height   Int?         @map("i_height")
    width    Int?         @map("i_width")
    duration Int?         @map("i_duration")
    type     CreativeType @map("e_creative_status")

    offer         Offer          @map("s_offer_id")
    creativeGroup CreativeGroup? @map("i_creative_group")

    @@map("tbl_creatives")
}

model Comment {
    id        String   @id @map("s_id") @default(cuid())
    text      String   @map("s_text")
    parentId  String   @map("s_parent_id")
    createdAt DateTime @map("dtu_creation") @default(now())
    updatedAt DateTime @map("dtu_last_update") @updatedAt

    createdBy      User            @map("s_user_id")
    campaignResult CampaignResult? @map("s_campaign_result_id")
    creativeGroup  CreativeGroup?  @map("s_creative_group_id")
    offer          Offer?          @map("s_offer_id")

    @@map("tbl_comments")
}

model Notification {
    id        String    @id @map("s_id") @default(cuid())
    name      String    @map("s_name")
    label     String    @map("s_label")
    language  String    @map("s_language")
    eventType EventType @map("e_event_type")
    category  Category  @map("s_category_id")

    notificationSetting NotificationSetting[]

    @@map("tbl_notifications")
}

model NotificationSetting {
    id           String             @id @map("s_id") @default(cuid())
    user         User               @map("s_user_id")
    notification Notification       @map("s_notification_setting_id")
    status       NotificationStatus @map("e_notification_status")

    @@map("tbl_notification_settings")
}

enum CreativeGroupStatus {
    New
    InProgress
    PendingApproval
    Approved
    Feedback
}

enum DeviceOS {
    Android
    IOS
    Other
}

enum RuleType {
    Create
    Read
    Update
    Delete
}

enum UserRole {
    Admin
    External
    Internal
}

enum EventType {
    OfferCreated
    OfferUpdated
    OfferDeleted
    CompanyCreated
    CompanyUpdated
    CompanyDeleted
    UserCreated
    UserUpdated
    UserDeleted
    CampaignResultCreated
    CampaignResultUpdated
    CampaignResultDeleted
    CampaignCreated
    CampaignUpdated
    CampaignDeleted
    NetworkCreated
    NetworkUpdated
    NetworkDeleted
    FileCreated
    FileUpdated
    FileDeleted
    CommentCreated
    CommentUpdated
    CommentDeleted
    CreativeGroupCreated
    CreativeGroupUpdated
    CreativeGroupDeleted
    CreativeCreated
    CreativeUpdated
    CreativeDeleted

    OfferPendingApproval
    OfferPendingRetestApproval
    OfferPendingChecks
    OfferAppReady
    OfferCampaignStarted
    OfferCampaignEnded
    OfferSigned
    OfferRejected

    CampaignActive
    CampaignFinished

    CreativeGroupInProgress
    CreativeGroupPendingApproval
    CreativeGroupFeedback
    CreativeGroupApproved

    UserInternalInvited
    UserExternalInvited
    UserInternalProfileComplete
    UserExternalProfileComplete
}

enum OfferEngine {
    Unity
    Native
}

enum OfferPriority {
    High
    Medium
    Low
}

enum OfferStatus {
    PendingApproval
    PendingChecks
    AppReady
    CampaignStarted
    CampaignEnded
    Signed
    Rejected
}

enum CreativeType {
    Image
    Video
    GIF
    PlayableAd
}

enum FileType {
    Attachment
    VideoRecording
    CreativeFile
    CreativeEndCard
    Picture
}

enum CampaignStatus {
    Waiting
    Active
    Finished
}

enum AdAccountsStatus {
    True
    False
    NoBusinessAccount
}

enum NetworkType {
    Facebook
    Irs
}

enum NotificationStatus {
    All
    Follower
    None
    Disabled
}
```

**Comment by tristancaron** [comment]
I run

1 - prisma2 lift save --name 'init'
2 - prisma2 lift up
3 - prisma2 generate

With no db in the directory

**Comment by pantharshit00** [comment]
@tristancaron Please open a new issue about this with your datamodel and OS information as well.

This seems unrelated to this issue so open a new issue and we handle it there 🙂
