### ISSUE TITLE
now dev sqlite

### ISSUE THREAD

**Issue by notrab** [prisma/prisma2#161]
```prisma
datasource db {
  provider = "sqlite"
  url      = "file:dev.db"
  default  = true
}
```

When running `now dev` returns the following error:

```bash
Database creation error: Sqlite data source must point to an existing file.
```

**Comment by divyenduz** [comment]
@notrab Since, now moves files over, it is not moving the sqlite file. I suggest using an absolute path for the SQLite file as a workaround for now.

**Comment by divyenduz** [comment]
Context: 

![image](https://user-images.githubusercontent.com/746482/63777632-b87f6980-c8e3-11e9-8624-2bd08bc8e565.png)

**Comment by divyenduz** [comment]
Even with an absolute path, I get an error like `<Table>.<Column>` does not exist. I think I am running into this one https://github.com/prisma/prisma2/issues/356

Once that is fixed, I will test this again with absolute paths. 

For relative paths, however, my current understanding is that zeit's team do not recommend that.

**Comment by divyenduz** [comment]
@pantharshit00 please try this again and see how it behaves now that #356 is fixed.

**Comment by pantharshit00** [comment]
This is still an issue. Looks like they are copying files to a temporary location in the dev flow.

![image](https://user-images.githubusercontent.com/22195362/64880013-dc2d0880-d674-11e9-81e3-03abff3b1a7c.png)

**Comment by pantharshit00** [comment]
Structure of the temporary location:
![image](https://user-images.githubusercontent.com/22195362/64880109-08488980-d675-11e9-8723-0439242a74f7.png)


I think maybe using absolute path might help here

**Comment by pantharshit00** [comment]
Works like a charm with a total absolute path:
![image](https://user-images.githubusercontent.com/22195362/64880287-74c38880-d675-11e9-8367-02020a875a7a.png)

I can't even use `~` to reference home in the path. This is very hacky but it works.

**Comment by pantharshit00** [comment]
I found an even better workaround that can make using SQLite in development very feasible(doesn't work in production as file permissions are messed up and make the database read-only: #681)

You can resolve the DB path programmatically in the photon constructor:

```
const photon = new Photon({
  datasources: {
    db: path.join(__dirname, 'prisma', 'test.db'),
  },
})
```

**Comment by divyenduz** [comment]
I am closing this one due to inactivity, if you still think that this is an issue, please comment here and tag me. Thank you 🙏
