### ISSUE TITLE
`prisma2 init` does not find `ts-node` when using starter kit "GraphQL API (+ Auth)"

### ISSUE THREAD

**Issue by nickreynke** [prisma/prisma2#482]
Using Prisma 2 version: `prisma2@2.0.0-preview-9.1, binary version: bbbeff6f84b408e534ebd866bfd378748e6d6611`

When running `prisma2 init` with the GraphQL API (+ Auth)starter kit I came across the following error. I assume that the `npm install` did not install everything:

```bash
...

✔  Downloading the starter kit from GitHub ...

Preparing your starter kit: GraphQL API (+ Auth)

✔  Downloading the starter kit from GitHub ...
✔  Extracting content to prisma2preview91 ...
✔  Installing dependencies with: `npm install` ...
✔  Preparing your database ...
⠼  Seeding your database with: `npm run seed` ...
 ERROR  Error during command execution

sh: ts-node: command not found
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! graphql-auth@ seed: `ts-node prisma/seed.ts`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the graphql-auth@ seed script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/nickreynke/.npm/_logs/2019-09-02T17_20_11_738Z-debug.log
```

After running a `npm i` I could run `npm run seed` successfully.

**Comment by pantharshit00** [comment]
I can confirm this. It is an easy workaround for now as you just need to run `npm install` again.

**Comment by nickreynke** [comment]
Still occurs in version `prisma2@2.0.0-preview-10, binary version: 1b0c271f14ca00606f56c93717e228fe48c5603c`

**Comment by ttsirkia** [comment]
`npm install -g typescript ts-node ts-node-dev` seems to be sufficient for the starter kits.

**Comment by divyenduz** [comment]
@ttsirkia Yes, the issue however is that these dev deps exist and are installed but for some reason `ts-node` doesn't go through. I will investigate this soon.

**Comment by divyenduz** [comment]
On further digging, I can confirm that using the [`bin.ts` from introspection directly](https://github.com/prisma/prisma2/blob/master/cli/prisma2/src/bin.ts#L43-L61) works but when it is used from [Prisma 2 CLI's `bin.ts` it fails](https://github.com/prisma/prisma2/blob/master/cli/prisma2/src/bin.ts#L43-L61) with this error as we pass in a different `cwd`. 

That is used here and it breaks the `ts-node` resolution: https://github.com/prisma/lift/blob/master/src/cli/commands/LiftTmpPrepare.ts#L9-L42

Tim informed me that a proper fix for this is to refactor the `cwd` resolution for Prisma schema path resolution which is a relatively larger refactor. 

Handing this one over to @timsuchanek

**Comment by timsuchanek** [comment]
Fixed in the latest alpha.

**Comment by divyenduz** [comment]
I can still reproduce this with `alpha.216`

**Comment by nickreynke** [comment]
Can confirm that the same procedure still fails when using version `prisma2@2.0.0-preview-13, binary version: 14576370b55d5152d9cb90f4f509bfa56760dbbd`.

**Comment by timsuchanek** [comment]
Apologies for the problems! We released a patch to fix this!
