### ISSUE TITLE
Prisma lift error: ambiguous self-relation detected

### ISSUE THREAD

**Issue by iherger** [prisma/prisma2#488]
I accidentally had an error in a data model definition, which lead to a self-referencing model (`related` should have been pointing to a different model `B`, and not to `A` ):
```graphql
model A {
  id      String @default(cuid()) @id @unique
  name    String    
  related A[] 
}
```
With this data model:
* the first invocation of `prisma2 lift save/up` was successful.
* further invocations of `prisma2 lift save/up` failed silently. Debugging showed the error message `"Ambiguous self relation detected."`

Expected behaviour:
1. at the first invocation of `prisma2 lift save/up`, report the `"Ambiguous self relation detected."` message, and prevent the creation of the ambiguous self relation.
2. don't fail silently, but actually display the error message

**Comment by pantharshit00** [comment]
Hi,

I am unable to reproduce this. The exact steps I took are:
1. prisma2 init
2. Added the model and migrated the datamodel using lift:
```groovy
model A {
  id      String @default(cuid()) @id @unique
  name    String    
  related A[] 
}
```
3. Added the further model to the datamodel and remigrated using lift:
```groovy
model B {
  id   String @default(cuid()) @id
  name String
  test Int
}
```
3. Deployment was successful and the underlying data structure is correct.
![image](https://user-images.githubusercontent.com/22195362/64252574-f4947900-cf38-11e9-8947-e5dda367afe0.png)

**Comment by divyenduz** [comment]
I am able to repro this: https://github.com/divyendu-test/p2-488

Thanks to a nice and shiny debugging session with @momakes

**Comment by imVinayPandya** [comment]
I am facing same issue, any solution/work around for this?

**Comment by divyenduz** [comment]
@imVinayPandya We will work on this in this sprint 👍

**Comment by perlo27** [comment]
After getting this error, is there any way to fall back? 
I've tried to delete migration and change back .prisma file, but still having this error, probably it's cached somewhere?

**Comment by tomhoule** [comment]
This should be fixed by https://github.com/prisma/prisma-engine/pull/82

The problem was that we weren't separating between models when validating that relation fields weren't causing any ambiguity, so there were false positives. The fix will be in the next preview :)

The PR also contains another change that makes the check for ambiguity in self relationships (model fields that refer to the same model) stricter.

Before, with this model:

```groovy
model Human {
    id Int @id
    parent Human
    child Human
}
```

we would have inferred a single self-relation with `parent` and `child` as the two ends.

Now this model is invalid, you need to specify whether you want two self relations or one, by using `@relation("NameOfTheRelation")`.

More info on this change in this schema spec PR: https://github.com/prisma/specs/pull/201

**Comment by divyenduz** [comment]
Reopening while this is not in alpha 🙏

**Comment by AbdusamadTurdiev** [comment]
> I accidentally had an error in a data model definition, which lead to a self-referencing model (`related` should have been pointing to a different model `B`, and not to `A` ):
> 
> ```graphql
> model A {
>   id      String @default(cuid()) @id @unique
>   name    String    
>   related A[] 
> }
> ```
> 
> With this data model:
> 
> * the first invocation of `prisma2 lift save/up` was successful.
> * further invocations of `prisma2 lift save/up` failed silently. Debugging showed the error message `"Ambiguous self relation detected."`
> 
> Expected behaviour:
> 
> 1. at the first invocation of `prisma2 lift save/up`, report the `"Ambiguous self relation detected."` message, and prevent the creation of the ambiguous self relation.
> 2. don't fail silently, but actually display the error message

I had the same schema and everything was good, but today after adding some new fields I've started to get this error

![image](https://user-images.githubusercontent.com/33511684/66153073-431a5d80-e634-11e9-9596-633aa86a1918.png)

Here's my schema

![image](https://user-images.githubusercontent.com/33511684/66153187-79f07380-e634-11e9-91d6-ff9a770c7cc9.png)

I tried this `friends User[] @relation(name: "UserFriends")` but I'm still getting error

**Comment by iaarab** [comment]
I get this error while running the `prisma2 init hello-prisma` and selecting photon only:

![image](https://user-images.githubusercontent.com/38687515/66194383-9e7c3800-e694-11e9-854e-053499de0d96.png)

**Comment by janpio** [comment]
Both @iaarab and @AbdusamadTurdiev, please both open a new issue and include all the relevant information so that what we can reproduce and later investigate what is going on. (The individual steps how you get your schema, and the schema as text (if possible) would help a lot.

**Comment by AbdusamadTurdiev** [comment]
is this going to be fixed guys?

**Comment by pantharshit00** [comment]
@AbdusamadTurdiev This has been fixed in the engine by https://github.com/prisma/prisma-engine/pull/82  as mentioned by @tomhoule. 

This hasn't been released yet so we have kept the PR open

**Comment by mavilein** [comment]
A fix for this was merged to alpha 9 days ago. It will be released as a normal preview tomorrow.
Forgot to close this.

**Comment by nhuesmann** [comment]
@mavilein I am still having this issue in `prisma2@2.0.0-preview014, binary version: 188a379c9b8c6650e5812f9bdb7407d7b197692f`. Preview 14 states it fixes this bug. Should I open a new issue, or post my schema here?

**Comment by mavilein** [comment]
@nhuesmann : Open a new one please 🙏

**Comment by nhuesmann** [comment]
@mavilein done: https://github.com/prisma/prisma2/issues/752
