### ISSUE TITLE
`prisma2 dev` hangs after creating SQLite database

### ISSUE THREAD

**Issue by janpio** [prisma/prisma2#641]
(`prisma2@2.0.0-preview-13.1, binary version: 14576370b55d5152d9cb90f4f509bfa56760dbbd`)

`prisma2 init foo` with `Blank project > SQLite > Confirm > JavaScript > Demo script` successfully creates project. After `cd ..` into the folder, when you run `prisma2 dev` you first get this, which is nice:

```
C:\Users\Jan\Documents\throwaway\hotfix2>prisma2 dev
You are trying to run prisma2 dev for Sqlite database dev.db.
A database with that name doesn't exist at file:dev.db.
Do you want to create the database?

┌─ Database options ─────────────────────────────────────────────────────────────────────────────────────────────────┐
│                                                                                                                    │
│ > Yes            Create new Sqlite database dev.db                                                                 │
│   No             Don't create the database                                                                         │
│                                                                                                                    │
└────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘
```

![image](https://user-images.githubusercontent.com/183673/65870869-7da6a080-e37d-11e9-8411-7ca037445691.png)

Unfortunately upon selecting "Yes", the text goes away and it just hangs with a blinking cursor:

![cursor_blinking](https://user-images.githubusercontent.com/183673/65871012-d24a1b80-e37d-11e9-85ad-1e91505f1040.gif)

There also doesn't seem to be a way out of there besides killing the terminal that is running this, Ctrl+C does nothing.

(This has to be confirmed to not be a Windows only or problem)

**Comment by divyenduz** [comment]
I can reproduce this with SQLite but not with MySQL.

**Comment by janpio** [comment]
Same problem still exists in `2.0.0-preview-13.2`.

Identical problem exists for `Blank project > SQLite > Confirm > JavaScript > Just the Prisma schema` - so all the Blank project SQLite flows seem broken right now.

**Comment by jferrettiboke** [comment]
I can confirm this on Windows 10 with `2.0.0-preview-13.2`.

**Comment by janpio** [comment]
This also affects the `Starter Kit` flow as it calls `prisma2 dev` in the background:

Reported by @nikolasburk in https://github.com/prisma/prisma2/issues/673:

> The CLI is hanging on the last screen at the `Preparing your database ...` step:
> 
> ![image](https://user-images.githubusercontent.com/4058327/66296809-acc59080-e8ee-11e9-9e89-0b0d33d9c645.png)
> 
> To reproduce, use version `preview-13.2`:
> 
> ```
> prisma2 init graphql-demo
> ```
> 
> Then select:
> 
> 1. Starter kit
> 2. TypeScript
> 3. GraphQL API
> 4. SQLite

**Comment by janpio** [comment]
This was fixed in `2.0.0-preview013.3` which is now available.

**Comment by MarvinAmador7** [comment]
This still exists in `prisma2@2.0.0-preview013.3, binary version: 2b78c35cf302bf80ae5aaa863c5eee0d09541f83`

Following the tutorial from https://github.com/prisma/prisma2/blob/master/docs/tutorial.md using a PostGres DB from digital ocean

**Comment by janpio** [comment]
Please create a new issues @MarvinAmador7, we did not look into digital ocean and postgres here. Thanks! (Possible there is already an issue about that, I vaguely remember something about DO and creating databases not being possible...)
