### ISSUE TITLE
Cannot use DateTime, getting error: Provided Json, expected DateTime

### ISSUE THREAD

**Issue by tomitrescak** [prisma/prisma2#809]
Hi I have a following model:

```
model BpmnProcessInstance {
  dateStarted   DateTime
} 
```

When trying to create a new record with 

```js
await photon.bpmnProcessInstances.create({
      data: {
        dateStarted: new Date(),
      }
})
```

I am receiving this error:

```
Argument dateStarted: Got invalid value {} on photon.createOneBpmnProcessInstance. Provided Json, expected DateTime. 
```

How can I use dates in my app?

**Comment by tomitrescak** [comment]
The only way I found this to work was to send date in strng format:

await photon.bpmnProcessInstances.create({
      data: {
        dateStarted: new Date().toISOString(),
      }
})

**Comment by pantharshit00** [comment]
I can't reproduce this with `prisma2@2.0.0-preview014.2, binary version: 237b46b97773f5018e336550e4285e2a78c38483`

**Comment by pantharshit00** [comment]
This was fixed in https://github.com/prisma/photonjs/commit/218b74906a2ee146976082ce30bd9111432301ec

Can you please try again in the latest version?

**Comment by tomitrescak** [comment]
Hi, I am using the version 015 and I am still getting this error.

**Comment by tomitrescak** [comment]
FYI: my date fields are created by Photon as following: `date?: Date | string | null;`

**Comment by pantharshit00** [comment]
Can you please make sure you have run `prisma2 dev` after you have updated your prisma2 version.

I still can't reproduce this:
![image](https://user-images.githubusercontent.com/22195362/67754292-84850980-fa36-11e9-9dbb-15a74a128f84.png)

**Comment by Constans** [comment]
Some DateTime issue occurs on my side also.

I have a **seenAt DateTime[]** array in my schema and when I query for that, it returns **{ seenAt: Invalid Date }** with no records for it, instead of an empty array [].

The primsa2 version is 015.

**Comment by Constans** [comment]
The workaround for this is to check if the result is an array, and if is not to initialise it to be an array:

```
if(Array.isArray(seenAt) == false) {
    seenAt = [];
}
```

**Comment by tomitrescak** [comment]
I must be doing something wrong but I am receiving the error.


Version
```
prisma2@2.0.0-preview015, binary version: 20b6dc13949cccccfef5be07c0be7a3d7c858abe
```

Model:

```
model Data {
  id         String  @default(cuid()) @id
  createdAt         DateTime?         @default(now())
  updatedAt         DateTime?         @updatedAt
  version           DateTime?
}
```

code

```ts
await ctx.db.data.create({
  data: {
    version: new Date()
  }
});
```

Result:

```
Invalid `photon.data.create()` invocation in ./src/resolvers/bpmn_task_instance/task_instance_resolver.js:102:53 
     
    { 
      data: { 
        version: {} 
        ~~~~~~~ 
      } 
    } 

Argument version: Got invalid value {} on photon.createOneData. Provided Json, expected DateTime. 
```

I did delete the '@generated` folder and re-run `yarn prisma2 generate`

Any advice?

**Comment by tomitrescak** [comment]
Maybe you can point me to some code in the generated files to see whether it is all generated correctly?

**Comment by tomitrescak** [comment]
Hi, this was really blocking me so I found the culprit, which unfortunately is a "bug" in your code. Sometimes the dates get somehow mangled and your condition for `if (value instanceof Date)` in `getGraphQLType` function becomes unstable (e.g. when passed across frame boundaries.).

Thus the safest way to test this is to do `if (Object.prototype.toString.call(value) === '[object Date]'`

After this all worked ... I did a PR prisma/photonjs#285

**Comment by pantharshit00** [comment]
Thanks for the PR. I have @timsuchanek to review it.

I am still unable to reproduce this though even after pasting the exact code that you have shared. Can you please tell me the node js version that you are using?

**Comment by tomitrescak** [comment]
Hi, it is 12.0.8.
This issue was a bit puzzling. This kept happening when used with Wallaby.js.
On first test run the correct date was passed. On second test run the Date was not passed as instance of Date. It is a bit difficult situation to explain, but overall the solution should lead to a bit more stable state.

**Comment by pantharshit00** [comment]
Did you try executing the script instead of executing it via wallaby? Otherwise might be a bug in wallaby.

**Comment by timsuchanek** [comment]
Thanks a lot for looking into this @tomitrescak !
Fixed in latest alpha by https://github.com/prisma/photonjs/pull/285.
You can try it out with `npm i -g prisma2@alpha`.

**Comment by dimaip** [comment]
I seem to be getting the same behaviour with Prisma 4.12.

This breaks:

```
prisma.deed.upsert({
        create: { someDate: new Date() },
        update: someData,
        where: {...},
      }
    )
```

While changing it to `new Date().toISOString()` fixes it.
