### ISSUE TITLE
Type Aliases not working

### ISSUE THREAD

**Issue by yovanoc** [prisma/prisma2#896]
Hello I see since one of the latest alpha I can't use my custom type.

![image](https://user-images.githubusercontent.com/7302317/68378579-a5431280-014c-11ea-827c-a91e4e23fdb6.png)

![image](https://user-images.githubusercontent.com/7302317/68378593-ab38f380-014c-11ea-93e5-2e943232cf99.png)

PS: this error happen while `prisma2 lift up`

**Comment by pantharshit00** [comment]
I can confirm this bug.

**Comment by mavilein** [comment]
I cannot reproduce this with the following version:
```
➜  type-alias-test prisma2 version
prisma2@2.0.0-preview015, binary version: 20b6dc13949cccccfef5be07c0be7a3d7c858abe
```

**Comment by mavilein** [comment]
Nevermind my comment. I forgot `-g` in my `npm install` command 🤦‍♂

**Comment by mavilein** [comment]
This is a regression of our new approach of diffing datamodels. The new diffing algorithm cannot handle type aliases as of now.

**Comment by tomhoule** [comment]
This should be fixed by https://github.com/prisma/prisma-engine/pull/183 - the fix will be in `prisma2@alpha` soon, and in the next preview version :)

**Comment by tomhoule** [comment]
I'll close the issue, but feel free to re-open if the problem persists.

**Comment by yovanoc** [comment]
still happening to me with `prisma2@2.0.0-alpha.334, binary version: b72fd0a786adc77ba6c61d0a9637ff0371e433b0`

**Comment by tomhoule** [comment]
Oh :/ Does the custom type appear in the migration when you `prisma2 lift save`?

**Comment by yovanoc** [comment]
No, that's why I get this error I guess

**Comment by pantharshit00** [comment]
I can confirm this still occurs in `prisma2@2.0.0-alpha.338, binary version: b72fd0a786adc77ba6c61d0a9637ff0371e433b0`

**Comment by tomhoule** [comment]
I just checked and your binary version (`b72fd0a786adc77ba6c61d0a9637ff0371e433b0`) is older than the fix - the new preview that is coming out soon should have the fix.

**Comment by janpio** [comment]
@pantharshit00 Can you please double check if this occurs with the new `preview017` release?

**Comment by pantharshit00** [comment]
Ok, I am not able to reproduce this now with preview-017.

Also, a quick note that you will need to delete the migrations both from the database and locally. They contain the wrong steps.

**Comment by nhuesmann** [comment]
Related to this issue, in Preview 17 I have been having a weird issue with custom types. I'm using the same type alias as the issue creator (CUID as an abstraction of `String @id @default(cuid())`). When I try to perform a migration with `prisma2 lift up`, I get an error stating that type `CUID` already exists—it seems like regardless of the changes I make to my schema, the `lift up` operation is trying to recreate the custom type.

**Comment by pantharshit00** [comment]
@nhuesmann I can confirm that bug.

I opened a new issue about there here: https://github.com/prisma/lift/issues/225

**Comment by nhuesmann** [comment]
@pantharshit00 great, thank you!
