### ISSUE TITLE
[Netlify] Cannot find module '@generated/photon/package.json'

### ISSUE THREAD

**Issue by kripod** [prisma/prisma2#952]
When using [a monorepo](https://github.com/kripod/exigo) to separate the client and server code, [the following](https://app.netlify.com/sites/exigo/deploys/5dd30d74a36b450008a3f6af) happens:

> 10:32:36 PM: Function Dir: /opt/build/repo/server/build/functions
> 10:32:36 PM: TempDir: /tmp/zisi-5dd30d74a36b450008a3f6af
> 10:32:36 PM: Prepping functions with zip-it-and-ship-it 0.4.0-7
> 10:32:38 PM: Error: In file "/opt/build/repo/server/build/functions/graphql.js": Cannot find module '@generated/photon/package.json' from '/opt/build/repo/server/build/graphql'
> 10:32:38 PM: Error prepping functions
> 10:32:38 PM: Error running command: Build script returned non-zero exit code: 1

I'm not sure about how to make `@generated/photon` (located at `server/node_modules`) discoverable by Netlify's [zip-it-and-ship-it](https://github.com/netlify/zip-it-and-ship-it) package. Will transitioning to the [facade package `@prisma/photon`](https://github.com/prisma/photonjs/issues/261) solve this automatically? What measures may I take to mitigate the issue until then?

**Comment by pantharshit00** [comment]
Yes, facade should solve this problem. Right now `@generated/photon` is not in your package.json file so netlify will eliminate it from the function environment.


I'd say you should wait till package facede is released.

**Comment by kripod** [comment]
@pantharshit00 Thank you for the quick response! As I'm working on a project with a tight deadline, could you provide a rough estimation about when the transition will be done?

**Comment by pantharshit00** [comment]
I can't promise a timeline as facade need some research and implementation. Currently, we are in the process of implementing it. In the meanwhile, you can deploy your application to something like digitalocean.

**Comment by kripod** [comment]
In the meantime, I’ve opened a PR to mitigate the issue: https://github.com/prisma-labs/nexus-prisma/pull/536

**Comment by pantharshit00** [comment]
@kripod Facade will be released in today's release(Preview 17) so please check that out :)

**Comment by seawatts** [comment]
I just tried out Preview 17 and it doesn't seem to be working. 
Seeing this issue still: https://github.com/prisma/prisma2/issues/625

**Comment by seawatts** [comment]
I'm also seeing these WARNINGS when using `netlify serve`

```
WARNING in ../node_modules/@prisma/photon/runtime/index.js 9724:18-25
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 @ ../node_modules/@prisma/photon/index.js
 @ ./hello.ts

WARNING in ../node_modules/@prisma/photon/runtime/index.js 30402:14-40
Critical dependency: the request of a dependency is an expression
 @ ../node_modules/@prisma/photon/index.js
 @ ./hello.ts
Lambda server is listening on 9000
```

**Comment by pantharshit00** [comment]
Please checkout the netlify deploy example: https://github.com/prisma/prisma-examples/tree/prisma2/deployment-platforms/netlify

**Comment by seawatts** [comment]
When trying to run `netlify serve` I still get those warnings.

And when I try to run `prisma2 generate` I get this error
```
Error: The `platforms` field on the generator definition is deprecated. Please rename it to `binaryTargets`.
```

When I switch `platforms` to `binaryTargets` it runs generate fine. But I still get this error on invocation

```
Request from ::1: GET /.netlify/functions/hello
Response with status 500 in 528 ms.
Error during invocation:  Error: Error in Photon: 
Error: Photon binary for current platform darwin could not be found.
Photon looked in null but couldn't find it.
Make sure to adjust the generator configuration in the schema.prisma file:
generator photon {
  provider      = "photonjs"
  binaryTargets = ["native", "rhel-openssl-1.0.x", "darwin"]
}
Please run prisma2 generate for your changes to take effect.
Note, that by providing `native`, Photon automatically resolves `darwin`.
Read more about deploying Photon: https://github.com/prisma/prisma2/blob/master/docs/core/generators/photonjs.md
    at NodeEngine.getPrismaPath (~/bot-slack/lambda/hello.js:1:894920)
    at async ~/bot-slack/lambda/hello.js:1:896510
    at u.<anonymous> (~/bot-slack/lambda/hello.js:1:2379)
    at Generator.throw (<anonymous>)
    at u (~/bot-slack/lambda/hello.js:1:1380)
```

Here is my generator section of my schema.prisma
```
generator photon {
  provider = "photonjs"
  binaryTargets = ["native", "rhel-openssl-1.0.x"]
}
```

Even if I try adding `darwin` to that list it still errors, and just adds another `darwin` to the error message.

```
Make sure to adjust the generator configuration in the schema.prisma file:
generator photon {
  provider      = "photonjs"
  binaryTargets = ["native", "rhel-openssl-1.0.x", "darwin", "darwin"]
}
```

**Comment by pantharshit00** [comment]
The command is called `netlify dev`. I think you might be using an outdated version of the netlify cli.

I am using the following version:
```
netlify-cli/2.21.0 darwin-x64 node-v10.16.0
```

**Comment by kripod** [comment]
This issue has been resolved by the introduction of the `@prisma/photon` facade package. Thanks for all the inputs!

**Comment by seawatts** [comment]
I am using the netlify lambda cli. Not the netlify cli. And no it's still not resolved

**Comment by pantharshit00** [comment]
@seawatts Can you please try https://github.com/prisma/prisma-examples/tree/prisma2/deployment-platforms/netlify with netlify cli? We haven't tested it with netlify-lambda and the build script that copies the binaries adhere to netlify cli.

**Comment by janpio** [comment]
@seawatts Also, if you have the time please open a new issue about the Netlify _Lambda_ CLI. We very much want to look into this and properly handle it if possible.

**Comment by seawatts** [comment]
Thanks that works now with `netlify dev`. Will do 👍

**Comment by seawatts** [comment]
I actually don't think defining the output to be the following is needed.

```
generator photon {
    provider       = "photonjs"
    output         = "./functions/generated/photon"
```

**Comment by seawatts** [comment]
I also got it working without that custom build deploy step. Just deploy like normal.

**Comment by pantharshit00** [comment]
Yes, we need to update that guide along with other cloud platforms. Thanks for sharing. Z
